autoAssign/apps/accounts/urls.py
# Urls.py file for accounts app
from django.urls import path
from .views import login_view, logout_view, home_view, create_user


urlpatterns = [
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('create_user/', create_user, name='create_user'),
]

autoAssign/apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('assignments/', views.assignment_list, name='assignment_list'),
    path('upload/', views.upload, name='upload'),
    path('all_delegates/', views.all_delegates_list, name='all_delegates'),
    path('unverified_delegates/', views.unverified_delegates, name='unverified_delegates'),
    path('paid_unassigned_delegates/', views.paid_unassigned_delegates, name='paid_unassigned_delegates'),
    path('paid_assigned_delegates/', views.paid_assigned_delegates, name='paid_assigned_delegates'),
    # path('paid-delegates/', views.paid_delegates, name='paid_delegates'),
    path('verify_payment/<int:delegate_id>/', views.verify_payment, name='verify_payment'),
    path('assign_delegate/<int:delegate_id>/', views.assign_delegate, name='assign_delegate'),
    path('update_delegate/<int:delegate_id>/', views.update_delegate, name='update_delegate'), 
    path('test_email/', views.test_email, name='test_email'),  # Add this line
    path('register_delegate/', views.register_delegate, name='register_delegate'),
    path('registration_success/', views.registration_success, name='registration_success'),
   path('assignment_report_form/', views.assignment_report_form, name='assignment_report_form'),
    path('generate_assignment_pdf/', views.generate_assignment_pdf, name='generate_assignment_pdf'),
    # Add other URL patterns here
]

autoAssign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("autoAssign.apps.accounts.urls")),
    path("app/", include("autoAssign.apps.core.urls")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

autoAssign/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    ROLE_CHOICES = [
        ('admin', 'Administrator'),
        ('finance', 'Finance'),
        ('delegates_affairs', 'Delegates Affairs'),
    ]
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='delegates_affairs')

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="customuser_set",
        related_query_name="user",
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="customuser_set",
        related_query_name="user",
    )

    def __str__(self):
        return self.username

autoAssign/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

ROLE_CHOICES = [
        ('admin', 'Administrator'),
        ('finance', 'Finance'),
        ('delegate_affairs', 'Delegate Affairs'),
    ]


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    role = forms.ChoiceField(choices=ROLE_CHOICES, required=True, widget=forms.Select(attrs={'class': 'form-control form-select'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'role')
        help_texts = {
            'username': None,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        if 'password2' in self.fields:
            self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['password2'].label = "Confirm Password"
        self.fields['password2'].help_text = None
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['password1'].label = "Password"
        self.fields['password1'].help_text = None
    

autoAssign/apps/accounts/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import LoginForm, CustomUserCreationForm #SignUpForm


def home_view(request):
    return HttpResponseRedirect(reverse('login'))

def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("core:dashboard")
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "accounts/login.html", {"form": form, "msg": msg})

def logout_view(request):
    logout(request)
    return redirect('login')


@login_required
@user_passes_test(lambda u: u.is_superuser)  # Only superusers can create users
def create_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.role = form.cleaned_data['role']  # Save the role
            user.save()
            messages.success(request, 'User created successfully.')
            return redirect(reverse('core:dashboard'))  # Redirect to the delegates list
        else:
            messages.error(request, 'There was an error creating the user.')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/create_user.html', {'form': form})

autoAssign/apps/core/views.py
import random
import json
# import io for the generation of PDF
import io
from django.http import JsonResponse, FileResponse
import datetime
import pandas as pd
from django.conf import settings
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.core.mail import EmailMessage, send_mail
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required, user_passes_test
from decouple import config
from django.core.management import call_command
from .forms import UploadForm, PaymentForm, DelegateForm, DelegateRegistrationForm
from .models import Delegate, Committee, Assignment, Payment
from django.db.models import Q
from django.template.loader import render_to_string
from weasyprint import HTML


# Define role-based access control functions
def is_admin(user):
    return user.is_authenticated and user.role == 'admin'

def is_finance(user):
    return user.is_authenticated and user.role == 'finance'

def is_delegates_affairs(user):
    return user.is_authenticated and user.role == 'delegates_affairs'


# Create your views here.
@login_required
def dashboard(request):
    total_delegates = Delegate.objects.count()
    assigned_delegates = Assignment.objects.count()
    paid_delegates = Payment.objects.filter(verified=True).count()
    recent_assignments = Assignment.objects.order_by('-id')[:10]
    percentage_paid = (paid_delegates / total_delegates) * 100 if total_delegates > 0 else 0

    context = {
        'total_delegates': total_delegates,
        'assigned_delegates': assigned_delegates,
        'paid_delegates': paid_delegates,
        'recent_assignments': recent_assignments,
        'current_date': datetime.datetime.now(),
        'percentage_paid': round(percentage_paid, 4)
    }

    return render(request, 'core/dashboard.html', context)


def register_delegate(request):
    committees = Committee.objects.all()
    committee_countries = {}
    for committee in committees:
        assigned_countries = Assignment.objects.filter(committee=committee.committee).values_list('country', flat=True)
        available_countries = [country.strip() for country in committee.countries.split(',') if country.strip() not in assigned_countries]
        committee_countries[committee.committee] = available_countries
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            delegate = Delegate(
                user_id=generate_unique_user_id(),
                name=data.get('name'),
                email=data.get('email'),
                phone=data.get('phone'),
                delegate_type=data.get('delegate_type'),
                gender=data.get('gender'),
                mun_experience=data.get('mun_experience'),
                affiliation=data.get('affiliation'),
                position=data.get('position'),
                department=data.get('department'),
                matric_num=data.get('matric_num'),
                city=data.get('city'),
                state=data.get('state'),
                country=data.get('country'),
                zipcode=data.get('zipcode'),
                advert=data.get('advert'),
                tshirt_size=data.get('tshirt_size'),
                medical=data.get('medical'),
                diet=data.get('diet'),
                referral=data.get('referral'),
                committee1=data.get('committee1'),
                country1=data.get('country1'),
                committee2=data.get('committee2'),
                country2=data.get('country2'),
                committee3=data.get('committee3'),
                country3=data.get('country3'),
                status = "Unassigned"
            )
            delegate.save()
            messages.success(request, 'Registration successful!')
            return JsonResponse({'status': 'success', 'message': 'Registration successful!', 'email': delegate.email}, status=201)
        except Exception as e:
            messages.error(request, f'Error during registration: {str(e)}')
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
    else:
        return render(request, 'core/register_delegate.html',{'committees': committees,'committee_countries': committee_countries})


def generate_unique_user_id():
    import uuid
    return str(uuid.uuid4())


def registration_success(request):
    query = request.GET.get('q')
    delegate = None

    if query:
        delegate = Delegate.objects.filter(name__icontains=query).first() or Delegate.objects.filter(email__icontains=query).first()

    return render(request, 'core/registration_success.html', {'delegate': delegate, 'query': query})


@login_required
@user_passes_test(lambda user: is_admin(user) or is_delegates_affairs(user))
def assignment_list(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    committee = request.GET.get('committee')

    if query:
        assignments = Assignment.objects.filter(delegate__name__icontains=query) | Assignment.objects.filter(delegate__email__icontains=query)
    else:
        assignments = Assignment.objects.all()
    
    if committee:
        assignments = assignments.filter(committee=committee)

    paginator = Paginator(assignments, int(page_size))  # Show 10 assignments per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    committees = Committee.objects.all()

    return render(request, 'core/assignment_list.html', {'page_obj': page_obj, 'query': query, 'page_size': page_size, 'committees': committees})

@login_required
def all_delegates_list(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    if query:
        delegates = Delegate.objects.filter(name__icontains=query) | Delegate.objects.filter(email__icontains=query)
    else:
        delegates = Delegate.objects.all()

    paginator = Paginator(delegates, int(page_size))  # Show 10 delegates per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'title': 'All Delegates',
        'description': 'Here is a list of all delegates',
        'query': query,
        'page_size': page_size
    }
    return render(request, 'core/delegates_list.html', context)


@login_required
def unverified_delegates(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    unverified_delegate_ids = Delegate.objects.filter(payment__isnull=True).values_list('id', flat=True)
    if query:
        delegates = Delegate.objects.filter(id__in=unverified_delegate_ids).filter(name__icontains=query) | Delegate.objects.filter(id__in=unverified_delegate_ids).filter(email__icontains=query)
    else:
        delegates = Delegate.objects.filter(id__in=unverified_delegate_ids)

    paginator = Paginator(delegates, int(page_size))  # Show 10 delegates per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'title': 'Unverified Delegates',
        'description': 'Delegates with unverified payments',
        'query': query,
        'page_size': page_size
    }
    return render(request, 'core/delegates_list.html', context)

@login_required
def paid_unassigned_delegates(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    paid_delegate_ids = Payment.objects.filter(verified=True).values_list('delegate_id', flat=True)
    unassigned_delegates = Delegate.objects.filter(id__in=paid_delegate_ids, assignment__isnull=True)

    if query:
        delegates = unassigned_delegates.filter(name__icontains=query) | unassigned_delegates.filter(email__icontains=query)
    else:
        delegates = unassigned_delegates

    paginator = Paginator(delegates, int(page_size))  # Show 10 delegates per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'title': 'Paid but Unassigned Delegates',
        'description': 'Delegates with verified payments but not yet assigned',
        'query': query,
        'page_size': page_size
    }
    return render(request, 'core/delegates_list.html', context)


@login_required
def paid_assigned_delegates(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    paid_delegate_ids = Payment.objects.filter(verified=True).values_list('delegate_id', flat=True)
    assigned_delegates = Delegate.objects.filter(id__in=paid_delegate_ids, assignment__isnull=False)

    if query:
        delegates = assigned_delegates.filter(name__icontains=query) | assigned_delegates.filter(email__icontains=query)
    else:
        delegates = assigned_delegates

    paginator = Paginator(delegates, int(page_size))  # Show 10 delegates per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'title': 'Paid and Assigned Delegates',
        'description': 'Delegates with verified payments and assigned',
        'query': query,
        'page_size': page_size  # Pass page_size to template
    }
    return render(request, 'core/delegates_list.html', context)

# @login_required
# def paid_delegates(request):
#     query = request.GET.get('q')
#     paid_delegate_ids = Payment.objects.filter(verified=True).values_list('delegate_id', flat=True)
#     if query:

autoAssign/templates/includes/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Filters</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger active-color">
            <div class="badge-colors ml-auto mr-auto">
              <span class="badge filter badge-purple" data-color="purple"></span>
              <span class="badge filter badge-azure" data-color="azure"></span>
              <span class="badge filter badge-green" data-color="green"></span>
              <span class="badge filter badge-warning" data-color="orange"></span>
              <span class="badge filter badge-danger" data-color="danger"></span>
              <span class="badge filter badge-rose active" data-color="rose"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="header-title">Images</li>
        <li class="active">
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-1.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-2.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-3.jpg" alt="">
          </a>
        </li>
        <li>
          <a class="img-holder switch-trigger" href="javascript:void(0)">
            <img src="/static/assets/img/sidebar-4.jpg" alt="">
          </a>
        </li>
        {% comment %} <li class="button-container">
          <a target="_blank" rel="noopener noreferrer"
             href="https://appseed.us/admin-dashboards" class="btn btn-default btn-block">
             More Templates
          </a>
        </li>
        <li class="button-container">
          <a target="_blank" rel="noopener noreferrer" 
             href="https://appseed.us" class="btn btn-primary btn-block">
             AppSeed
          </a>
        </li> {% endcomment %}
      </ul>
    </div>
  </div>

autoAssign/templates/includes/footer.html
    <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>

              <li>
                <a target="_blank" rel="noopener noreferrer" 
                   href="https://appseed.us/admin-dashboards/django-dashboard-material">
                   RUIMUN AutoAssign
                </a>
              </li>

            </ul>
          </nav>
          <div class="copyright float-right">
            &copy; <a target="_blank" rel="noopener noreferrer" 
                      href="https://bit.ly/3fKQZaL">Creative Tim AppSeed</a> 
                      - coded by <a target="_blank" rel="noopener noreferrer" href="https://johnjaylawal.me">John J. Lawal</a>
          </div>
        </div>
    </footer>

autoAssign/templates/includes/navigation-rtl.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">داشبورد</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    آمارها
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    اعلان‌ها
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">محمدرضا به ایمیل شما پاسخ داد</a>
                  <a class="dropdown-item" href="#">شما ۵ وظیفه جدید دارید</a>
                  <a class="dropdown-item" href="#">از حالا شما با علیرضا دوست هستید</a>
                  <a class="dropdown-item" href="#">اعلان دیگر</a>
                  <a class="dropdown-item" href="#">اعلان دیگر</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="/page-user.html">Profile</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}" >Log out</a>
                </div>
              </li>
            </ul>
          </div>

        </div>
      </nav>

autoAssign/templates/includes/navigation.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
      <div class="navbar-wrapper">
          <a class="navbar-brand" href="#pablo">RUIMUN AutoAssign Dashboard</a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon icon-bar"></span>
          <span class="navbar-toggler-icon icon-bar"></span>
          <span class="navbar-toggler-icon icon-bar"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end">
          {% if request.user.is_authenticated %}
          <ul class="navbar-nav">
              {% if messages %}
              {% for message in messages %}
              <li class="nav-item">
                  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
              </li>
              {% endfor %}
              {% endif %}
              <li class="nav-item dropdown">
                  <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="material-icons">person</i>
                      <p class="d-lg-none d-md-block">
                          Account
                      </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                    <a class="dropdown-item" href="{% url 'create_user' %}">Create User</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
              </li>
          </ul>
          {% endif %}
      </div>
  </div>
</nav>

autoAssign/templates/includes/sidebar.html
<div class="sidebar" data-color="purple" data-background-color="white" data-image="/static/assets/img/sidebar-1.jpg">
  <div class="logo">
    <a target="_blank" rel="noopener noreferrer" 
       href="{url 'core:dashboard'}" class="simple-text logo-normal">
      RUIMUN
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      {% if request.user.is_authenticated %}
        <li class="nav-item {% if 'dashboard' in request.path %} active {% endif %}">
          <a class="nav-link" href="{% url 'core:dashboard' %}">
            <i class="material-icons">dashboard</i>
            <p>Dashboard</p>
          </a>
        </li>
        <li class="nav-item {% if 'delegates' in request.path %} active {% endif %}">
          <a class="nav-link" data-toggle="collapse" href="#delegatesMenu" aria-expanded="false">
            <i class="material-icons">people</i>
            <p>Delegates</p>
          </a>
          <div class="collapse" id="delegatesMenu">
            <ul class="nav">
              <li class="nav-item {% if 'all-delegates' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'core:all_delegates' %}">
                  <i class="material-icons">list</i>
                  <p>All Delegates</p>
                </a>
              </li>
                <li class="nav-item {% if 'paid-unassigned-delegates' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'core:paid_unassigned_delegates' %}">
                  <i class="material-icons">assignment_late</i>
                  <p>Paid but Unassigned Delegates</p>
                </a>
                </li>
                <li class="nav-item {% if 'paid-assigned-delegates' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'core:paid_assigned_delegates' %}">
                  <i class="material-icons">assignment_turned_in</i>
                  <p>Paid and Assigned Delegates</p>
                </a>
                </li>
                <li class="nav-item {% if 'unverified-delegates' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'core:unverified_delegates' %}">
                  <i class="material-icons">assignment_late</i>
                  <p>Unverified Delegates</p>
                </a>
                </li>
            </ul>
          </div>
        </li>
        <li class="nav-item {% if 'assignments' in request.path %} active {% endif %}">
          <a class="nav-link" href="{% url 'core:assignment_list' %}">
            <i class="material-icons">assignment</i>
            <p>Assignments</p>
          </a>
        </li>
        <li class="nav-item {% if 'upload' in request.path %} active {% endif %}">
          <a class="nav-link" href="{% url 'core:upload' %}">
            <i class="material-icons">cloud_upload</i>
            <p>Upload Data</p>
          </a>
        </li>
        <li class="nav-item {% if 'upload' in request.path %} active {% endif %}">
          <a class="nav-link" href="{% url 'core:assignment_report_form' %}">
            <i class="material-icons">assessment</i>
            <p>Reports</p>
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'logout' %}">
            <i class="material-icons">directions_run</i>
            <p>Logout</p>
          </a>
        </li>
      {% else %}
        {% comment %} <li class="nav-item active">
          <a class="nav-link" 
             target="_blank" rel="noopener noreferrer"  
             href="https://appseed.us/admin-dashboards/django-dashboard-material-pro">
            <i class="material-icons">unarchive</i>
            <p>PRO Version</p>
          </a>
        </li> {% endcomment %}
      {% endif %}
    </ul>
  </div>
</div>