autoAssign/apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('assignments/', views.assignment_list, name='assignment_list'),
    path('upload/', views.upload, name='upload'),
    path('all_delegates/', views.all_delegates_list, name='all_delegates'),
    path('unverified_delegates/', views.unverified_delegates, name='unverified_delegates'),
    path('paid_unassigned_delegates/', views.paid_unassigned_delegates, name='paid_unassigned_delegates'),
    path('paid_assigned_delegates/', views.paid_assigned_delegates, name='paid_assigned_delegates'),
    # path('paid-delegates/', views.paid_delegates, name='paid_delegates'),
    path('verify_payment/<int:delegate_id>/', views.verify_payment, name='verify_payment'),
    path('assign_delegate/<int:delegate_id>/', views.assign_delegate, name='assign_delegate'),
    path('update_delegate/<int:delegate_id>/', views.update_delegate, name='update_delegate'), 
    path('test_email/', views.test_email, name='test_email'),  # Add this line
    path('register_delegate/', views.register_delegate, name='register_delegate'),
    path('registration_success/', views.registration_success, name='registration_success'),
   path('assignment_report_form/', views.assignment_report_form, name='assignment_report_form'),
    path('generate_assignment_pdf/', views.generate_assignment_pdf, name='generate_assignment_pdf'),
    # Add other URL patterns here
]

autoAssign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("autoAssign.apps.accounts.urls")),
    path("app/", include("autoAssign.apps.core.urls")),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

autoAssign/apps/core/forms.py
from django import forms
from .models import Payment, Delegate, Committee

class UploadForm(forms.Form):
    file = forms.FileField()

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['payment_method', 'amount']
        widgets = {
            'payment_method': forms.Select(attrs={'class': 'form-control form-select'}),
            'amount': forms.Select(attrs={'class': 'form-control form-select'}),
        }


class DelegateForm(forms.ModelForm):
    class Meta:
        model = Delegate
        fields = ['name', 'email', 'phone', 'delegate_type', 'gender', 'mun_experience', 'affiliation', 'position', 'department', 'matric_num', 'city', 'state', 'country', 'zipcode', 'advert', 'tshirt_size', 'medical', 'diet', 'referral', 'status']
        widgets = {
            'gender': forms.Select(attrs={'class': 'form-control form-select'}),
            'delegate_type': forms.Select(attrs={'class': 'form-control form-select'}),
            'mun_experience': forms.Textarea(attrs={'class': 'form-control'}),
            'affiliation': forms.TextInput(attrs={'class': 'form-control'}),
            'position': forms.TextInput(attrs={'class': 'form-control'}),
            'department': forms.TextInput(attrs={'class': 'form-control'}),
            'matric_num': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'zipcode': forms.TextInput(attrs={'class': 'form-control'}),
            'advert': forms.TextInput(attrs={'class': 'form-control form-select'}),
            'tshirt_size': forms.Select(attrs={'class': 'form-control form-select'}),
            'medical': forms.Textarea(attrs={'class': 'form-control'}),
            'diet': forms.Textarea(attrs={'class': 'form-control'}),
            'referral': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control form-select'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }


class DelegateRegistrationForm(forms.ModelForm):
    class Meta:
        model = Delegate
        fields = [
            'name', 'email', 'phone', 'delegate_type', 'gender',
            'mun_experience', 'affiliation', 'position', 'department',
            'matric_num', 'city', 'state', 'country', 'zipcode',
            'advert', 'tshirt_size', 'medical', 'diet', 'referral',
            'committee1', 'country1', 'committee2', 'country2',
            'committee3', 'country3'
        ]
        widgets = {
            'gender': forms.Select(attrs={'class': 'form-control form-select'}),
            'delegate_type': forms.Select(attrs={'class': 'form-control form-select'}),
            'mun_experience': forms.Textarea(attrs={'class': 'form-control'}),
            'affiliation': forms.TextInput(attrs={'class': 'form-control'}),
            'position': forms.TextInput(attrs={'class': 'form-control'}),
            'department': forms.TextInput(attrs={'class': 'form-control'}),
            'matric_num': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'zipcode': forms.TextInput(attrs={'class': 'form-control'}),
            'advert': forms.Select(attrs={'class': 'form-control form-select'}),
            'tshirt_size': forms.Select(attrs={'class': 'form-control form-select'}),
            'medical': forms.Textarea(attrs={'class': 'form-control'}),
            'diet': forms.Textarea(attrs={'class': 'form-control'}),
            'referral': forms.TextInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'committee1': forms.Select(attrs={'class': 'form-control'}),
            'country1': forms.TextInput(attrs={'class': 'form-control'}),
            'committee2': forms.Select(attrs={'class': 'form-control'}),
            'country2': forms.TextInput(attrs={'class': 'form-control'}),
            'committee3': forms.Select(attrs={'class': 'form-control'}),
            'country3': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        committee_choices = [(committee.committee, committee.committee) for committee in Committee.objects.all()]
        self.fields['committee1'].choices = [('', 'Select Committee')] + committee_choices
        self.fields['committee2'].choices = [('', 'Select Committee')] + committee_choices
        self.fields['committee3'].choices = [('', 'Select Committee')] + committee_choices

autoAssign/apps/core/views.py
import random
import json
# import io for the generation of PDF
import io
from django.http import JsonResponse, FileResponse
import datetime
import pandas as pd
from django.conf import settings
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.core.mail import EmailMessage, send_mail
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required, user_passes_test
from decouple import config
from django.core.management import call_command
from .forms import UploadForm, PaymentForm, DelegateForm, DelegateRegistrationForm
from .models import Delegate, Committee, Assignment, Payment
from django.db.models import Q
from django.template.loader import render_to_string
from weasyprint import HTML


# Define role-based access control functions
def is_admin(user):
    return user.is_authenticated and user.role == 'admin'

def is_finance(user):
    return user.is_authenticated and user.role == 'finance'

def is_delegates_affairs(user):
    return user.is_authenticated and user.role == 'delegates_affairs'


# Create your views here.
@login_required
def dashboard(request):
    total_delegates = Delegate.objects.count()
    assigned_delegates = Assignment.objects.count()
    paid_delegates = Payment.objects.filter(verified=True).count()
    recent_assignments = Assignment.objects.order_by('-id')[:10]
    percentage_paid = (paid_delegates / total_delegates) * 100 if total_delegates > 0 else 0

    context = {
        'total_delegates': total_delegates,
        'assigned_delegates': assigned_delegates,
        'paid_delegates': paid_delegates,
        'recent_assignments': recent_assignments,
        'current_date': datetime.datetime.now(),
        'percentage_paid': round(percentage_paid, 4)
    }

    return render(request, 'core/dashboard.html', context)


def register_delegate(request):
    committees = Committee.objects.all()
    committee_countries = {}
    for committee in committees:
        assigned_countries = Assignment.objects.filter(committee=committee.committee).values_list('country', flat=True)
        available_countries = [country.strip() for country in committee.countries.split(',') if country.strip() not in assigned_countries]
        committee_countries[committee.committee] = available_countries
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            delegate = Delegate(
                user_id=generate_unique_user_id(),
                name=data.get('name'),
                email=data.get('email'),
                phone=data.get('phone'),
                delegate_type=data.get('delegate_type'),
                gender=data.get('gender'),
                mun_experience=data.get('mun_experience'),
                affiliation=data.get('affiliation'),
                position=data.get('position'),
                department=data.get('department'),
                matric_num=data.get('matric_num'),
                city=data.get('city'),
                state=data.get('state'),
                country=data.get('country'),
                zipcode=data.get('zipcode'),
                advert=data.get('advert'),
                tshirt_size=data.get('tshirt_size'),
                medical=data.get('medical'),
                diet=data.get('diet'),
                referral=data.get('referral'),
                committee1=data.get('committee1'),
                country1=data.get('country1'),
                committee2=data.get('committee2'),
                country2=data.get('country2'),
                committee3=data.get('committee3'),
                country3=data.get('country3'),
                status = "Unassigned"
            )
            delegate.save()
            messages.success(request, 'Registration successful!')
            return JsonResponse({'status': 'success', 'message': 'Registration successful!', 'email': delegate.email}, status=201)
        except Exception as e:
            messages.error(request, f'Error during registration: {str(e)}')
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
    else:
        return render(request, 'core/register_delegate.html',{'committees': committees,'committee_countries': committee_countries})


def generate_unique_user_id():
    import uuid
    return str(uuid.uuid4())


def registration_success(request):
    query = request.GET.get('q')
    delegate = None

    if query:
        delegate = Delegate.objects.filter(name__icontains=query).first() or Delegate.objects.filter(email__icontains=query).first()

    return render(request, 'core/registration_success.html', {'delegate': delegate, 'query': query})


@login_required
@user_passes_test(lambda user: is_admin(user) or is_delegates_affairs(user))
def assignment_list(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    committee = request.GET.get('committee')

    if query:
        assignments = Assignment.objects.filter(delegate__name__icontains=query) | Assignment.objects.filter(delegate__email__icontains=query)
    else:
        assignments = Assignment.objects.all()
    
    if committee:
        assignments = assignments.filter(committee=committee)

    paginator = Paginator(assignments, int(page_size))  # Show 10 assignments per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    committees = Committee.objects.all()

    return render(request, 'core/assignment_list.html', {'page_obj': page_obj, 'query': query, 'page_size': page_size, 'committees': committees})

@login_required
def all_delegates_list(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    if query:
        delegates = Delegate.objects.filter(name__icontains=query) | Delegate.objects.filter(email__icontains=query)
    else:
        delegates = Delegate.objects.all()

    paginator = Paginator(delegates, int(page_size))  # Show 10 delegates per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'title': 'All Delegates',
        'description': 'Here is a list of all delegates',
        'query': query,
        'page_size': page_size
    }
    return render(request, 'core/delegates_list.html', context)


@login_required
def unverified_delegates(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    unverified_delegate_ids = Delegate.objects.filter(payment__isnull=True).values_list('id', flat=True)
    if query:
        delegates = Delegate.objects.filter(id__in=unverified_delegate_ids).filter(name__icontains=query) | Delegate.objects.filter(id__in=unverified_delegate_ids).filter(email__icontains=query)
    else:
        delegates = Delegate.objects.filter(id__in=unverified_delegate_ids)

    paginator = Paginator(delegates, int(page_size))  # Show 10 delegates per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'title': 'Unverified Delegates',
        'description': 'Delegates with unverified payments',
        'query': query,
        'page_size': page_size
    }
    return render(request, 'core/delegates_list.html', context)

@login_required
def paid_unassigned_delegates(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    paid_delegate_ids = Payment.objects.filter(verified=True).values_list('delegate_id', flat=True)
    unassigned_delegates = Delegate.objects.filter(id__in=paid_delegate_ids, assignment__isnull=True)

    if query:
        delegates = unassigned_delegates.filter(name__icontains=query) | unassigned_delegates.filter(email__icontains=query)
    else:
        delegates = unassigned_delegates

    paginator = Paginator(delegates, int(page_size))  # Show 10 delegates per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'title': 'Paid but Unassigned Delegates',
        'description': 'Delegates with verified payments but not yet assigned',
        'query': query,
        'page_size': page_size
    }
    return render(request, 'core/delegates_list.html', context)


@login_required
def paid_assigned_delegates(request):
    query = request.GET.get('q')
    page_size = request.GET.get('page_size', '10')  # Default to 10
    paid_delegate_ids = Payment.objects.filter(verified=True).values_list('delegate_id', flat=True)
    assigned_delegates = Delegate.objects.filter(id__in=paid_delegate_ids, assignment__isnull=False)

    if query:
        delegates = assigned_delegates.filter(name__icontains=query) | assigned_delegates.filter(email__icontains=query)
    else:
        delegates = assigned_delegates

    paginator = Paginator(delegates, int(page_size))  # Show 10 delegates per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'title': 'Paid and Assigned Delegates',
        'description': 'Delegates with verified payments and assigned',
        'query': query,
        'page_size': page_size  # Pass page_size to template
    }
    return render(request, 'core/delegates_list.html', context)

# @login_required
# def paid_delegates(request):
#     query = request.GET.get('q')
#     paid_delegate_ids = Payment.objects.filter(verified=True).values_list('delegate_id', flat=True)
#     if query:

autoAssign/apps/core/templates/core/assignment_list.html
{% extends "layouts/base.html" %}

{% block title %} Assignment List {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Assignment List</h4>
                <p class="card-category">Here is a list of all assignments</p>
                <p class="card-category">Total Assignments: <span class="badge badge-info">{{ page_obj.paginator.count }}</span></p>
                <form method="get" action="">
                    <div class="row">
                        <div class="col-md-4 mt-3">
                            <div class="form-group input-group no-border">
                                <label for="q">Search Delegate Name:</label>
                                <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Search...">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group input-group no-border">
                                <label for="page_size">Records per page:</label>
                                <select class="form-control" id="page_size" name="page_size">
                                    <option value="10" {% if page_size == '10' %}selected{% endif %}>10</option>
                                    <option value="20" {% if page_size == '20' %}selected{% endif %}>20</option>
                                    <option value="30" {% if page_size == '30' %}selected{% endif %}>30</option>
                                    <option value="40" {% if page_size == '40' %}selected{% endif %}>40</option>
                                    <option value="50" {% if page_size == '50' %}selected{% endif %}>50</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group input-group no-border">
                                <label for="committee">Filter by Committee:</label>
                                <select class="form-control" id="committee" name="committee">
                                    <option value="">All Committees</option>
                                    {% for committee in committees %}
                                    <option value="{{ committee.committee }}" {% if selected_committee == committee.committee %}selected{% endif %}>{{ committee.committee }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Apply Filters</button>
                </form>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <th>ID</th>
                            <th>Delegate</th>
                            <th>Committee</th>
                            <th>Country</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            {% for assignment in page_obj %}
                            <tr>
                                <td>{{ assignment.id }}</td>
                                <td>{{ assignment.delegate.name }}</td>
                                <td>{{ assignment.committee }}</td>
                                <td>{{ assignment.country }}</td>
                                <td>
                                    <a href="{% url 'core:assign_delegate' assignment.delegate.id %}" class="btn btn-info btn-sm">Re-Assign</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <span class="current">{{ num }}</span>
                            {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                                <a href="?page={{ num }}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                        
                        <a href="javascript:history.back()" class="btn btn-secondary">Go Back</a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

autoAssign/apps/core/templates/core/delegates_list.html
{% extends "layouts/base.html" %}

{% block title %} {{ title }} {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">{{ title }}</h4>
                <p class="card-category">{{ description }}</p>
                <p class="card-category">Total Delegates: <span class="badge badge-info">{{ page_obj.paginator.count }}</span></p>
                <form method="get" action="">
                    <div class="row">
                        <div class="col-md-4 mt-3">
                            <div class="form-group input-group no-border">
                                <label for="q">Search Delegate Name:</label>
                                <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Search...">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group input-group no-border">
                                <label for="page_size">Records per page:</label>
                                <select class="form-control" id="page_size" name="page_size">
                                    <option value="10" {% if page_size == '10' %}selected{% endif %}>10</option>
                                    <option value="20" {% if page_size == '20' %}selected{% endif %}>20</option>
                                    <option value="30" {% if page_size == '30' %}selected{% endif %}>30</option>
                                    <option value="40" {% if page_size == '40' %}selected{% endif %}>40</option>
                                    <option value="50" {% if page_size == '50' %}selected{% endif %}>50</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group input-group no-border">
                                <label for="committee">Filter by Committee:</label>
                                <select class="form-control" id="committee" name="committee">
                                    <option value="">All Committees</option>
                                    {% for committee in committees %}
                                    <option value="{{ committee.committee }}" {% if selected_committee == committee.committee %}selected{% endif %}>{{ committee.committee }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Apply Filters</button>
                </form>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Category</th>
                            <th>Actions</th>
                        </thead>
                        <tbody>
                            {% for delegate in page_obj %}
                            <tr>
                                <td>{{ delegate.id }}</td>
                                <td>{{ delegate.name }}</td>
                                <td>{{ delegate.email }}</td>
                                <td>{{ delegate.status }}</td>
                                <td>{{ delegate.delegate_type }}</td>
                                <td>
                                    {% if user.role == 'admin' or user.role == 'finance' %}
                                        {% if delegate.has_paid %}
                                            <button class="btn btn-success btn-sm">Update Payment</button>
                                        {% else %}
                                            <a href="{% url 'core:verify_payment' delegate.id %}?next={{ request.path|urlencode }}" class="btn btn-success btn-sm">Verify Payment</a>
                                        {% endif %}
                                    {% endif %}

                                    {% if user.role == 'admin' or user.role == 'delegates_affairs' %}
                                        <a href="{% url 'core:update_delegate' delegate.id %}?next={{ request.path|urlencode }}" class="btn btn-warning btn-sm">Update Details</a>
                                    {% endif %}

                                    {% if user.role == 'admin' or user.role == 'delegates_affairs' %}
                                        {% if delegate.status == 'Assigned' %}
                                            <a href="{% url 'core:assign_delegate' delegate.id %}?next={{ request.path|urlencode }}" class="btn btn-info btn-sm">Re-Assign</a>
                                        {% else %}
                                            <a href="{% url 'core:assign_delegate' delegate.id %}?next={{ request.path|urlencode }}" class="btn btn-info btn-sm">Assign</a>
                                        {% endif %}
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1&q={{ query|default:'' }}&page_size={{ page_size|default:'10' }}&committee={{ selected_committee|default:'' }}">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}&q={{ query|default:'' }}&page_size={{ page_size|default:'10' }}&committee={{ selected_committee|default:'' }}">previous</a>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <span class="current">{{ num }}</span>
                            {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                                <a href="?page={{ num }}&q={{ query|default:'' }}&page_size={{ page_size|default:'10' }}&committee={{ selected_committee|default:'' }}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}&q={{ query|default:'' }}&page_size={{ page_size|default:'10' }}&committee={{ selected_committee|default:'' }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}&q={{ query|default:'' }}&page_size={{ page_size|default:'10' }}&committee={{ selected_committee|default:'' }}">last &raquo;</a>
                        {% endif %}

                        <a href="javascript:history.back()" class="btn btn-secondary">Go Back</a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

autoAssign/apps/core/templates/core/update_delegate.html
{% extends "layouts/base.html" %}

{% block title %} Update Delegate Details {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Update Delegate Details</h4>
                <p class="card-category">Edit the details of the delegate</p>
                <a href="javascript:history.back()" class="btn btn-secondary">Go Back</a>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a href="{% url 'core:all_delegates' %}" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
            <div class="card-footer">
                <a href="javascript:history.back()" class="btn btn-secondary">Go Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}